export const white = '#FFFFFF'
export const lightGrey = '#F5F5F5'
export const disabledGrey = '#BBBBBB'
export const darkGrey = '#333333'
export const black = '#000000'
export const orange = '#F16550'
